# Generated by Django 3.0.4 on 2020-03-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChondoKotha', '0004_divisions_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='division_id',
            new_name='division',
        ),
    ]
